#FROM continuumio/anaconda3
FROM continuumio/anaconda3

MAINTAINER iljoong@outlook.com

WORKDIR /app
EXPOSE 8080

RUN apt-get update

RUN /opt/conda/bin/conda install -y -c menpo opencv 
RUN wget https://github.com/Azure/blobxfer/releases/download/1.3.1/blobxfer-1.3.1-linux-x86_64 \
    && mv blobxfer-1.3.1-linux-x86_64 /usr/local/bin/blobxfer \
    && chmod +x /usr/local/bin/blobxfer 

RUN mkdir /models

WORKDIR /src
COPY . .

RUN /opt/conda/bin/pip install -r pipinstall.txt
RUN /opt/conda/bin/pip install -U tensorflow

ENTRYPOINT ["/opt/conda/bin/python", "main.py", "-l", "debug"]
