#using built-in python3
FROM tensorflow/tensorflow:1.9.0-gpu-py3

MAINTAINER iljoong@outlook.com

WORKDIR /app
EXPOSE 8080

RUN apt-get update

RUN pip install opencv-python==3.2.0.8
RUN curl -L -o blobxfer-1.3.1-linux-x86_64 https://github.com/Azure/blobxfer/releases/download/1.3.1/blobxfer-1.3.1-linux-x86_64 \
    && mv blobxfer-1.3.1-linux-x86_64 /usr/local/bin/blobxfer \
    && chmod +x /usr/local/bin/blobxfer 

RUN mkdir /models

WORKDIR /src
COPY . .

RUN pip install -r pipinstall.txt

# additional installation
RUN pip install requests
RUN apt-get install zip

# for blobxfer for this base image
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENTRYPOINT ["python", "main.py", "-l", "debug"]
